"""empty message

Revision ID: 387044fd7665
Revises: 1057b5125345
Create Date: 2021-01-03 19:40:50.339880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387044fd7665'
down_revision = '1057b5125345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
